server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/EmsDjallil/EmsConfigurations.git
          username: mugiwaradz
          password: equilibriom6A
#  security:
#    user:
#      name: root
#      password: s3cr3t
